spring:
  application:
    name: crud-jdbc-demo-hbk
  h2:
    console:
      enabled: true   # H2-InMemory DB-console --> http://localhost:8080/h2-console (default) here i named as http://localhost:8080/h2
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb   # here testdb is name of database which is default
    driver-class-name: org.h2.Driver
    username: sa
    password:
